### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by FuShengACE** [chidiwilliams/buzz#584] opened 2023-08-21 18:59 UTC
Could you please develop a feature where, if I have the text transcript of an audio segment, the software can generate a matching subtitle file for that text?

**Comment by DeafNet** [comment] 2023-08-21 20:12
Agree with this person, please please please.

**Comment by chidiwilliams** [comment] 2023-09-02 11:34
Are you aware that the transcript viewer is editable? Does this fit your use case?

https://github.com/chidiwilliams/buzz/assets/17879672/ef3f9e22-b406-46f8-bba5-d9c12686be09

**Comment by DeafNet** [comment] 2023-10-02 04:16
What he mean is pretext breakdown add to buzz with audio and from there , ai can match those with timestamp

**Comment by raivisdejus** [comment] 2024-06-21 21:21
@FuShengACE Will close this as duplicate of https://github.com/chidiwilliams/buzz/issues/582. Please see comments there. In essence you need https://github.com/echogarden-project/echogarden/blob/main/docs/CLI.md#speech-to-transcript-alignment

**Closed by raivisdejus** 2024-06-21 21:21 UTC
