### ISSUE TITLE
Whisper.cpp + FastWhisper don't work

### ISSUE THREAD

**Issue by Dragoy** [chidiwilliams/buzz#468] opened 2023-05-25 00:56 UTC
When I start FastWhisper it reaches 0% and stops :

    [2023-05-25 02:50:21,348] transcriber.run:732 DEBUG -> Starting next transcription task [2023-05-25 02:50:21,356] transcriber.transcribe:436 DEBUG -> Starting whisper file transcription, task = FileTranscriptionTask(file_path='F:/VIDEO/!SRT_TRANSLATE/02.mp4', transcription_options=TranscriptionOptions(language='ko', task=<Task.TRANSCRIBE: 'transcribe'>, model=TranscriptionModel(model_type=<ModelType.FASTER_WHISPER: 'Faster Whisper'>, whisper_model_size=<WhisperModelSize.MEDIUM: 'medium'>, hugging_face_model_id=None), word_level_timings=False, temperature=(0.0, 0.2, 0.4, 0.6, 0.8, 1.0), initial_prompt='', openai_access_token=''), file_transcription_options=FileTranscriptionOptions(file_paths=['F:/VIDEO/!SRT_TRANSLATE/02.mp4'], output_formats=set()), model_path='C:\\Users\\Dragoy\\.cache\\huggingface\\hub\\models--guillaumekln--faster-whisper-medium\\snapshots\\8701f851d407f3f47e091bb13b8dac5290c7f7fb', id=709142, segments=[], status=<Status.QUEUED: 'queued'>, error=None) 
    [2023-05-25 02:51:18,485] transcriber.transcribe:458 DEBUG -> whisper process completed with code = 3221226505, time taken = 0:00:57.129357, number of segments = 0 
    [2023-05-25 02:51:18,485] transcriber.run:250 ERROR ->  Traceback (most recent call last):   File "buzz\transcriber.py", line 247, in run   File "buzz\transcriber.py", line 463, in transcribe Exception: Unknown error 
    [2023-05-25 02:51:18,485] transcriber.run:716 DEBUG -> Waiting for next transcription task

 
When I start Whisper.cpp it just creates an empty srt and exits without an error:

    [2023-05-25 02:54:15,198] transcriber.run:732 DEBUG -> Starting next transcription task
    [2023-05-25 02:54:15,204] transcriber.transcribe:296 DEBUG -> Starting whisper_cpp file transcription, file path = H:/1-40/03.mp4, language = ko, task = Task.TRANSCRIBE, model_path = C:\Users\Dragoy\AppData\Local\Buzz\Buzz\Cache\ggml-model-whisper-medium.bin, word level timings = False
    [2023-05-25 02:54:19,564] transcriber.transcribe:317 DEBUG -> Running whisper_cpp process, args = "--language ko --max-len 0 --model C:\Users\Dragoy\AppData\Local\Buzz\Buzz\Cache\ggml-model-whisper-medium.bin C:\Users\Dragoy\AppData\Local\Temp\tmptwtss432.wav"
    [2023-05-25 02:54:19,566] transcriber.transcribe:327 DEBUG -> whisper_cpp process completed with status = ExitStatus.NormalExit
    [2023-05-25 02:54:19,566] transcriber.write_output:591 DEBUG -> Writing transcription output, path = H:/1-40/03 (Transcribed on 25-May-2023 02-54-19).srt, output format = OutputFormat.SRT, number of segments = 0
    [2023-05-25 02:54:19,567] transcriber.run:716 DEBUG -> Waiting for next transcription task
    [2023-05-25 02:54:19,569] transcriber.write_output:617 DEBUG -> Written transcription output

**Comment by chidiwilliams** [comment] 2023-05-29 08:25
Marking as duplicate of #442

**Closed by chidiwilliams** 2023-05-29 08:25 UTC
