### ISSUE TITLE
I18n for Spanish is possible?

### ISSUE THREAD

**Issue by johnfelipe** [chidiwilliams/buzz#303] opened 2023-01-04 03:45 UTC
I want contribute with Spanish, french and Italian UI translation

**Comment by chidiwilliams** [comment] 2023-01-04 09:06
Yes, sure. There's been another request at #193, but I had prioritized some other tasks. I'll update this thread soon once I prepare the I18n for the app.

**Comment by chidiwilliams** [comment] 2023-01-04 18:44
Duplicate of #188

**Closed by chidiwilliams** 2023-01-04 18:44 UTC
