### ISSUE TITLE
Model download error

### ISSUE THREAD

**Issue by woyin** [chidiwilliams/buzz#256] opened 2022-12-19 11:46 UTC
<img width="421" alt="image" src="https://user-images.githubusercontent.com/35319250/208418750-239d0270-2a53-49d1-a52e-387941d78b76.png">
When I use the **very high** quality, I got the strong process bar.

**Comment by Ty-lerCox** [comment] 2022-12-19 21:23
Pretty sure that percentage is the bytes downloaded. That is likely 93MB/s. I'm downloading the very high model, its 3.1 GB. I have downloaded ~1.3 GB I think
![image](https://user-images.githubusercontent.com/6323925/208526763-68137c4c-d34f-45c3-854c-21e700fbf2b1.png)

**Comment by chidiwilliams** [comment] 2022-12-19 22:55
Yeah, noticed this as well 🥲 Looking into a fix soon.

**Comment by chidiwilliams** [comment] 2022-12-21 18:56
Duplicate of #219

**Closed by chidiwilliams** 2022-12-21 18:56 UTC
