### ISSUE TITLE
windows 11,  Whisper automatically exits the software after download

### ISSUE THREAD

**Issue by msjsc001** [chidiwilliams/buzz#251] opened 2022-12-16 19:40 UTC
After selecting VeryHigh, the software will automatically close when the download reaches 2GB without any error message, so I need to restart the software to download again, and then it will automatically close again when it reaches 2GB, and the download will not finish.
Is there a way to download Whisper directly? Instead of downloading through Buzz
![image](https://user-images.githubusercontent.com/93178788/208229434-e149ef22-f137-4053-9f41-a6d639a55e93.png)

![image](https://user-images.githubusercontent.com/93178788/208229508-18db77e1-d30b-47e1-965e-10b5ea4174e9.png)

**Comment by msjsc001** [comment] 2022-12-17 06:47
After selecting VeryHigh, the software will automatically close when the download reaches 2GB without any error message, so I need to restart the software to download again, and then it will automatically close again when it reaches 2GB, and the download will not finish.
Is there a way to download Whisper directly? Instead of downloading through Buzz
![image](https://user-images.githubusercontent.com/93178788/208229434-e149ef22-f137-4053-9f41-a6d639a55e93.png)

**Comment by chidiwilliams** [comment] 2022-12-21 18:55
Duplicate of #219

**Closed by chidiwilliams** 2022-12-21 18:55 UTC
Labels: duplicate
