### ISSUE TITLE
If GPU operations can be implemented, the extraction speed should be much faster

### ISSUE THREAD

**Issue by martjay** [chidiwilliams/buzz#302] opened 2023-01-04 02:33 UTC
If GPU operations can be implemented, the extraction speed should be much faster, The CPU mode is still too slow.

**Comment by martjay** [comment] 2023-01-04 02:38
https://github.com/openai/whisper/discussions/47

**Comment by martjay** [comment] 2023-01-04 02:48
It will also be convenient to implement a batch task list, otherwise you will have to start tasks one by one each time

**Comment by chidiwilliams** [comment] 2023-01-04 09:08
Sure, I haven't figured out the GPU yet. But I'll mark this as a duplicate of #182 for now.

**Comment by chidiwilliams** [comment] 2023-01-04 09:08
> https://s3.bmp.ovh/imgs/2023/01/04/936aad75fd9795aa.jpg
> 
> I can't find .srt file

I don't have access to the image. Maybe a permissions issue?

**Comment by martjay** [comment] 2023-01-04 14:27
> 

https://www.imgurl.org/img/936aad75fd9795aa

**Comment by martjay** [comment] 2023-01-04 14:28
> > https://s3.bmp.ovh/imgs/2023/01/04/936aad75fd9795aa.jpg
> > I can't find .srt file
> 
> I don't have access to the image. Maybe a permissions issue?

https://www.imgurl.org/img/936aad75fd9795aa

**Comment by martjay** [comment] 2023-01-05 07:00
![Uploading 777777.jpg…]()

**Comment by xxx975** [comment] 2023-01-05 07:07
u can try select this line and click third ico

**Comment by xxx975** [comment] 2023-01-05 07:08
this line == 3 Levels of Chords - ........  
:)

**Comment by martjay** [comment] 2023-01-05 08:14
> this line == 3 Levels of Chords - ........ :)

Thank you. In this way, the subtitles can be exported. I think the subtitles will be automatically exported to the video directory

**Comment by esonec** [comment] 2023-01-05 18:35
Followed the steps from here
https://github.com/openai/whisper/discussions/47

For me now: "CUDA enabled: True"

But the Buzz still runs on the CPU. While they say, Whisper should detect CUDA and run on GPU.

**Comment by chidiwilliams** [comment] 2023-01-05 19:01
> > this line == 3 Levels of Chords - ........ :)
> 
> Thank you. In this way, the subtitles can be exported. I think the subtitles will be automatically exported to the video directory

Yes, the behaviour changed in the last release. Double-clicking the line also works :)

**Comment by martjay** [comment] 2023-01-06 05:41
> Followed the steps from here [openai/whisper#47](https://github.com/openai/whisper/discussions/47)
> 
> For me now: "CUDA enabled: True"
> 
> But the Buzz still runs on the CPU. While they say, Whisper should detect CUDA and run on GPU.

Using GPU mode will be much faster than using CPU. I really don't cheat you

**Comment by martjay** [comment] 2023-01-06 05:42
> 

Can't the latest version automatically generate the srt to the video directory? I think automatic generation is more convenient

**Comment by martjay** [comment] 2023-01-06 05:43
> > > this line == 3 Levels of Chords - ........ :)
> > 
> > 
> > Thank you. In this way, the subtitles can be exported. I think the subtitles will be automatically exported to the video directory
> 
> Yes, the behaviour changed in the last release. Double-clicking the line also works :)

Can't the latest version automatically generate the srt to the video directory? I think automatic generation is more convenient

**Comment by ttimasdf** [comment] 2023-01-07 05:16
Currently, pytorch with CUDA support is only available if you manually install pytorch build supporting CUDA inside poetry virtualenv. You also need to uninstall previous build with pip.

https://github.com/openai/whisper/discussions/47#discussioncomment-4549820

Follow the steps above, then apply the following patch.

```diff
diff --git a/buzz/transcriber.py b/buzz/transcriber.py
index c087c13..c489d9a 100644
--- a/buzz/transcriber.py
+++ b/buzz/transcriber.py
@@ -424,7 +424,8 @@ def transcribe_whisper(stderr_conn: Connection, task: FileTranscriptionTask):
                                       task=task.transcription_options.task.value, verbose=False)
             whisper_segments = result.get('segments')
         else:
-            model = whisper.load_model(task.model_path)
+            logging.info("Loading whisper with CUDA device")
+            model = whisper.load_model(task.model_path, device="cuda")
             if task.transcription_options.word_level_timings:
                 stable_whisper.modify_model(model)
                 result = model.transcribe(
```

**Comment by ttimasdf** [comment] 2023-01-08 15:30
Changes I made to install pytorch through poetry. Tested on windows.

```diff
diff --git a/pyproject.toml b/pyproject.toml
index 2ffef1f..12a60ea 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -10,13 +10,15 @@ readme = "README.md"
 python = ">=3.9.13,<3.11"
@@ -10,13 +10,15 @@ readme = "README.md"
 python = ">=3.9.13,<3.11"
 sounddevice = "^0.4.5"
 whisper = { git = "https://github.com/openai/whisper.git" }
-torch = "1.12.1"
+torch = {version = "^1.13.1+cu117", source = "pytorch-cu117"}
 transformers = "~4.24.0"
 appdirs = "^1.4.4"
 ffmpeg-python = "^0.2.0"
 humanize = "^4.4.0"
 PyQt6 = "^6.4.0"
+stable-ts = "^1.0.2"
 tqdm = "^4.64.1"
+click = "^8.1.3"

 [tool.poetry.group.dev.dependencies]
 autopep8 = "^1.7.0"
@@ -30,6 +32,13 @@ pylint = "^2.15.5"
 pre-commit = "^2.20.0"
 ctypesgen = "^1.1.1"

+
+[[tool.poetry.source]]
+name = "pytorch-cu117"
+url = "https://download.pytorch.org/whl/cu117"
+default = false
+secondary = true
+
 [build-system]
 requires = ["poetry-core"]
 build-backend = "poetry.core.masonry.api"
```

**Comment by martjay** [comment] 2023-01-09 06:50
> Changes I made to install pytorch through poetry. Tested on windows.
> 
> ```diff
> diff --git a/pyproject.toml b/pyproject.toml
> index 2ffef1f..12a60ea 100644
> --- a/pyproject.toml
> +++ b/pyproject.toml
> @@ -10,13 +10,15 @@ readme = "README.md"
>  python = ">=3.9.13,<3.11"
> @@ -10,13 +10,15 @@ readme = "README.md"
>  python = ">=3.9.13,<3.11"
>  sounddevice = "^0.4.5"
>  whisper = { git = "https://github.com/openai/whisper.git" }
> -torch = "1.12.1"
> +torch = {version = "^1.13.1+cu117", source = "pytorch-cu117"}
>  transformers = "~4.24.0"
>  appdirs = "^1.4.4"
>  ffmpeg-python = "^0.2.0"
>  humanize = "^4.4.0"
>  PyQt6 = "^6.4.0"
> +stable-ts = "^1.0.2"
>  tqdm = "^4.64.1"
> +click = "^8.1.3"
> 
>  [tool.poetry.group.dev.dependencies]
>  autopep8 = "^1.7.0"
> @@ -30,6 +32,13 @@ pylint = "^2.15.5"
>  pre-commit = "^2.20.0"
>  ctypesgen = "^1.1.1"
> 
> +
> +[[tool.poetry.source]]
> +name = "pytorch-cu117"
> +url = "https://download.pytorch.org/whl/cu117"
> +default = false
> +secondary = true
> +
>  [build-system]
>  requires = ["poetry-core"]
>  build-backend = "poetry.core.masonry.api"
> ```

@chidiwilliams see, but I dont know how to do, pls update new version release~

**Closed** 2023-04-08 09:58 UTC
Labels: wontfix
