### ISSUE TITLE
Crash when deselecting TXT / SRT / VTT checkboxes - V0.8.1 - Win10 22H2

### ISSUE THREAD

**Issue by t0t061** [chidiwilliams/buzz#490] opened 2023-06-14 06:33 UTC
After completing a transcription, when I try to perform a new transcription, if I try to deselect the previously selected checkboxes, the application crashes, without any error message (only the mouse icon "rotates" a few seconds before the application closes).
The next time it is reopened, the checkboxes are still activated, and the problem recurs as soon as you try to uncheck one of the options.
To get round the problem, you need to 
- add a new audio/video file
- close the options window without changing anything (i.e. cancel what you're doing)
- add an audio/video file again. In this case, the options window is displayed with the TXT / SRT / VTT checkboxes unchecked.

https://github.com/chidiwilliams/buzz/assets/136443808/7a4700ca-1678-4723-8122-64e43909d963

**Comment by faveoled** [comment] 2023-06-16 18:52
Likely a duplicate of #479

**Comment by chidiwilliams** [comment] 2023-06-16 19:12
Yes it's been fixed. I'll make a new release once I get #486 done.

**Comment by chidiwilliams** [comment] 2023-06-20 17:09
Should be fixed in the latest release: https://github.com/chidiwilliams/buzz/releases/tag/v0.8.2

**Closed by chidiwilliams** 2023-06-20 17:09 UTC
